### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jlw4049** [jlw4049/BHDStudio-Upload-Tool#50]
Exception in thread Thread-3:Traceback (most recent call last):File "threading.py", line 932, in _bootstrap_innerFile "threading.py", line 870, in runFile "BHDStudioUploadTool.py", line 4943, in semi_automatic_screenshotsFile "src\cython\vapoursynth.pyx", line 1833, in vapoursynth.VideoNode.get_frameFile "src\cython\vapoursynth.pyx", line 1827, in vapoursynth.VideoNode.ensure_valid_frame_numberValueError:Requesting frame number is beyond the last frame

**Comment by jlw4049** [comment]
Detect total b frames and decrease the number manually/automatically
